### ISSUE TITLE
Keep loading on Ubuntu 18.10

### ISSUE THREAD

**Issue by plateena** [psukys/ulauncher-plugin-windows#1]
Nothing happen. The plugin stuck on loading...

**Comment by psukys** [comment]
This plugin relies on `wmctrl` package for querying the windows, is it available at your system, when you loaded the plugin?

**Comment by plateena** [comment]
Sorry din't know it relies on that plugin. Already install and it works.
Thanks

**Comment by psukys** [comment]
No problem, I'll clarify this  in README file
