### ISSUE TITLE
Port extension to Ulauncher 5

### ISSUE THREAD

**Issue by vipau** [psukys/ulauncher-plugin-windows#2]
Ulauncher 5 (of which development builds are already available) will ship the Python 3 version only. As a result, all extensions have to be ported to Python 3, and also the new Ulauncher Extension API v2.

See [more details here](http://docs.ulauncher.io/en/latest/extensions/migration.html#migrate-from-api-v1-to-v2-0-0)

**Comment by psukys** [comment]
Thanks for the headsup @paualberto will check it out!

**Comment by LinuxOnTheDesktop** [comment]
I too would like the extension updated, if I may say so.

**Comment by psukys** [comment]
@LinuxOnTheDesktop will push out the new version out today!

**Comment by psukys** [comment]
The extension has been updated and is available from the [uLauncher v5 list](https://ext.ulauncher.io/?api_version=2.0.0)
