### ISSUE TITLE
After typing "w" in search bar, It keeps loading...

### ISSUE THREAD

**Issue by smaqeelkazmi** [psukys/ulauncher-plugin-windows#5]
I have installed this extension for my Ulauncher:

OS: Ubuntu 18
Launcher: ULauncher

but after **w** It keeps loading and no results shows in result bar of ULauncher. For example
If I type: **w terminal**
no result comes.

Can u please have a look on this issue?

Thanks.

**Comment by draszek** [comment]
try `sudo apt install wmctrl` it should help :)
